#!/bin/bash

if [ ! -f ".env" ]
then
  echo "Creating .env -- update it with your API key!"
  cp .env.example .env
fi

if ! cmp -s "install" ".installed"; then
  echo "Installing stuff..."
  ./install
  cp install .installed
else
  echo "Looks like the installation has been run already. Skipping"
fi

export PYTHONUNBUFFERED=true # this says, "print output to the terminal immediately."
export FLASK_ENV=development

source .env

opentelemetry-instrument python3 server.py
